import { Component, EventEmitter, OnInit, Output, ViewChild } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Documentos } from './documentos.class';
import { DocumentosService } from './documentos.service';

@Component({
  selector: 'app-documentos',
  templateUrl: './documentos.component.html',
  styleUrls: ['./documentos.component.css']
})
export class DocumentosComponent implements OnInit {
  @ViewChild('form_document') form_document: NgForm;
  @Output() cancelarCreate = new EventEmitter<boolean>();
  public resultados = [];
  public procesando: boolean = false;
  public mostrar_listado: boolean = false;
  modoVer:boolean = false;
  datatable_optiones = {
    title: 'Documentos',
    empty_text: 'No existen datos que cumplan con el filtro seleccionado',
    mostrar_columns_excel: [false, false],
    mostrar_columns_pdf: [false, false],
    columns_headers: [
      { key: 'codigo_documento', label: 'Código', show: true, classnamebody:'codigo', classname:'codigo'},
      { key: 'nombre_documento', label: 'Nombre', show: true, classnamebody:"nombre", classname:"nombre" },
      { key: 'especialidad_nombre', label: 'Especialidad', show: true, classnamebody:"especialidad", classname:"especialidad"},
      { key: 'tipo_documento_nombre', label: 'Tipo', show: true, classnamebody:"tipo-documento", classname:"tipo-documento"},
      { key: 'fecha_documento', label: 'Fecha', show: true , pipe:'date', classnamebody:"fecha", classname:"fecha"},
      { key: 'numero_version', label: 'Versión Vigente', show: true, classnamebody:"version", classname:"version"},
      { key: 'estado_nom', label: 'Estado', show: true, classnamebody:"estado", classname:"estado"},
    ],
    columns_types: ['text', 'text', 'text', 'text', 'text','number','text'],
    options: { edit: true, view: false, delete: false, puntos: true },
    dropdown_options: [
      { label: 'Editar', action: 'editar', iconsvg: 'editar' },
      { label: 'Nueva versión', action: 'nueva_version', iconsvg: 'plus' },
      { label: 'Descargar', action: 'ver', iconclass: 'fa fa-download' },
      {
        label: 'Eliminar',
        classname: 'text-danger',
        action: 'eliminar',
        iconsvg: 'eliminar',
      },
    ],
    // para los hijjos

    columns_child_active:true,
     columns_headers_child_names:['versiones','versiones'],//test item fake
    //columns_headers_child_name:'versiones',
    columns_child: [
     // { key: 'nombre_division', label: 'Clase', show: true, classnamebody:'width600px' },
      { key: 'codigo_documento', label: 'Código', show: true, classnamebody:'codigo' },
      { key: 'nombre_documento', label: 'Nombre', show: true, classnamebody:'nombre'},
      { key: 'especialidad_nombre', label: 'Especialidad', show: true, classnamebody:'especialidad' },
      { key: 'tipo_documento_nombre', label: 'Tipo', show: true, classnamebody:'tipo-documento' },
      { key: 'fecha_documento', label: 'Fecha', show: true, pipe:'date', classnamebody:'fecha' },
      { key: 'numero_version', label: 'Versión Vigente', show: true, classnamebody:'version' },
      { key: 'estado_nom', label: 'Estado', show: true, classnamebody:'estado' }
    ],
    options_child: { edit: false, view: true, delete: false,puntos: false},

    columns_child_child: [
      // { key: 'nombre_division', label: 'Clase', show: true, classnamebody:'width600px' },
       { key: 'codigo_documento', label: 'Código', show: true, classnamebody:'codigo' },
       { key: 'nombre_documento', label: 'Nombre', show: true, classnamebody:'nombre'},
       { key: 'especialidad_nombre', label: 'Especialidad', show: true, classnamebody:'especialidad' },
       { key: 'tipo_documento_nombre', label: 'Tipo', show: true, classnamebody:'tipo-documento' },
       { key: 'fecha_documento', label: 'Fecha', show: true, pipe:'date', classnamebody:'fecha' },
       { key: 'numero_version', label: 'Versión Vigente', show: true, classnamebody:'version' },
       { key: 'estado_nom', label: 'Estado', show: true, classnamebody:'estado' }
     ],

    options_header: '',
    navigation_offsets: [5, 10, 15, 20, 50, 100, 200, 500, 1000, 2000],
    navigation_starting_offset_index: 5,
    show_search_field: true,
    show_toexcel: false,
    show_toexportar: false,
    show_toimportar: false,
    show_topdf: false,
    reserved_check: false, //Verifica si es reservado, seteamos a false para cargar los botonos edit, delete, view con normalidad
    reserved_column: 'operaciones',
    reserved_values: { value_true: 'NO', value_false: 'SI' },
    hide_bar_header: true,
    title_td: 'Detalle',
    show_number_elements: true,
  };

  steps: string[] = ['Caracterización', 'Formatos/Anexos', 'Documento General'];
  current_step: number = 0
  documento = new Documentos();
  listado_especialidad = [];
  listado_documentacion = [];
  public modo_consulta: boolean = false;

  title_archivo: string = 'Cargar Archivo';
  formato_descripcion: string = 'se aceptan formato .pdf';
  data_cargada: boolean = true;
  archivo_anexo: string = '';

  constructor(private service: DocumentosService) {

  }

  ngOnInit(): void {
    this.listar();
  }

  listar(){
    this.resultados=[
      {
        "id_documento": 28,
        "nombre_documento": "DOCUMENTO 01 TEST12",
        "codigo_documento": "TEST01",
        "fecha_documento": "2023-03-15",
        "numero_version": 7,
        "documento_general": "http://localhost:8000/media/documento/20230510225652QRS.pdf",
        "tipo_documento": 1,
        "especialidad": 1,
        "comentario": "null",
        "id_empresa": 1,
        "id_version_documento": 43,
        "versiones": [
          {
            "id_version_documento": 42,
            "estado_nom": "No Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOCUMENTO 01 TEST12",
            "codigo_documento": "TEST01",
            "comentario": null,
            "fecha_documento": "2023-03-31",
            "numero_version": 6,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-04-04T18:21:28.045701Z",
            "fecha_actualizacion": null,
            "estado": 0,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 28,
            "versiones": [
              {
                "id_version_documento": 42,
                "estado_nom": "Vigente",
                "tipo_documento_nombre": "Tipo NIETO",
                "especialidad_nombre": "ESPECIALIDAD NIETO",
                "nombre_documento": "DOCUMENTO NIETO",
                "codigo_documento": "NIETO",
                "comentario": null,
                "fecha_documento": "2023-03-31",
                "numero_version": 7,
                "documento_general": null,
                "sesion_id": null,
                "fecha_creacion": "2023-04-04T18:21:28.045701Z",
                "fecha_actualizacion": null,
                "estado": 0,
                "eliminado": 0,
                "tipo_documento": 1,
                "especialidad": 1,
                "documento": 28,
              },
              {
                "id_version_documento": 42,
                "estado_nom": "No Vigente",
                "tipo_documento_nombre": "Tipo NIETA",
                "especialidad_nombre": "Especialidad NIETA",
                "nombre_documento": "DOCUMENTO NIETA",
                "codigo_documento": "NIETA",
                "comentario": null,
                "fecha_documento": "2023-03-31",
                "numero_version": 8,
                "documento_general": null,
                "sesion_id": null,
                "fecha_creacion": "2023-04-04T18:21:28.045701Z",
                "fecha_actualizacion": null,
                "estado": 0,
                "eliminado": 0,
                "tipo_documento": 1,
                "especialidad": 1,
                "documento": 28,
              }
            ]
          },
          {
            "id_version_documento": 41,
            "estado_nom": "No Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOCUMENTO 01 TEST12",
            "codigo_documento": "TEST01",
            "comentario": null,
            "fecha_documento": "2023-03-31",
            "numero_version": 5,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-04-04T18:19:49.071318Z",
            "fecha_actualizacion": null,
            "estado": 0,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 28
          },
          {
            "id_version_documento": 40,
            "estado_nom": "No Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOCUMENTO 01 TEST12",
            "codigo_documento": "TEST01",
            "comentario": null,
            "fecha_documento": "2023-03-31",
            "numero_version": 4,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-04-03T14:42:16.180320Z",
            "fecha_actualizacion": null,
            "estado": 0,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 28
          },
          {
            "id_version_documento": 39,
            "estado_nom": "No Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOCUMENTO 01 TEST12",
            "codigo_documento": "TEST01",
            "comentario": null,
            "fecha_documento": "2023-03-31",
            "numero_version": 3,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-04-03T14:40:34.593643Z",
            "fecha_actualizacion": null,
            "estado": 0,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 28
          },
          {
            "id_version_documento": 38,
            "estado_nom": "No Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOCUMENTO 01 TEST12",
            "codigo_documento": "TEST01",
            "comentario": null,
            "fecha_documento": "2023-03-31",
            "numero_version": 2,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-03-31T18:12:52.260673Z",
            "fecha_actualizacion": null,
            "estado": 0,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 28
          },
          {
            "id_version_documento": 37,
            "estado_nom": "No Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOCUMENTO 01 TEST",
            "codigo_documento": "TEST01",
            "comentario": null,
            "fecha_documento": "2023-03-31",
            "numero_version": 1,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-03-31T18:08:28.583615Z",
            "fecha_actualizacion": null,
            "estado": 0,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 28
          }
        ],
        "tipo_documento_nombre": "Tipo 1",
        "especialidad_nombre": "Especialidad 1",
        "sesion_id": null,
        "fecha_creacion": "2023-03-31T18:08:28.557000Z",
        "fecha_actualizacion": null,
        "estado": 1,
        "estado_nom": "Vigente",
        "eliminado": 0
      },
      {
        "id_documento": 24,
        "nombre_documento": "DOC89",
        "codigo_documento": "DOC89",
        "fecha_documento": "2023-03-08",
        "numero_version": 4,
        "documento_general": null,
        "tipo_documento": 1,
        "especialidad": 1,
        "comentario": null,
        "id_empresa": 1,
        "id_version_documento": 33,
        "versiones": [
          {
            "id_version_documento": 33,
            "estado_nom": "Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOC89",
            "codigo_documento": "DOC89",
            "comentario": null,
            "fecha_documento": "2023-03-08",
            "numero_version": 1,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-03-31T17:28:22.371944Z",
            "fecha_actualizacion": null,
            "estado": 1,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 24
          }
        ],
        "tipo_documento_nombre": "Tipo 1",
        "especialidad_nombre": "Especialidad 1",
        "sesion_id": null,
        "fecha_creacion": "2023-03-29T22:02:38.518099Z",
        "fecha_actualizacion": null,
        "estado": 1,
        "estado_nom": "Vigente",
        "eliminado": 0
      },
      {
        "id_documento": 8,
        "nombre_documento": "DOC89",
        "codigo_documento": "DOC89",
        "fecha_documento": "2023-03-08",
        "numero_version": 4,
        "documento_general": null,
        "tipo_documento": 1,
        "especialidad": 1,
        "comentario": null,
        "id_empresa": 1,
        "id_version_documento": 24,
        "versiones": [
          {
            "id_version_documento": 17,
            "estado_nom": "No Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOC89",
            "codigo_documento": "DOC89",
            "comentario": null,
            "fecha_documento": "2023-03-08",
            "numero_version": 3,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-03-31T04:47:03.345546Z",
            "fecha_actualizacion": null,
            "estado": 0,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 8
          },
          {
            "id_version_documento": 15,
            "estado_nom": "No Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOC89",
            "codigo_documento": "DOC89",
            "comentario": null,
            "fecha_documento": "2023-03-08",
            "numero_version": 2,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-03-29T22:04:41.194495Z",
            "fecha_actualizacion": null,
            "estado": 0,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 8
          },
          {
            "id_version_documento": 14,
            "estado_nom": "No Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOC89",
            "codigo_documento": "DOC89",
            "comentario": null,
            "fecha_documento": "2023-03-08",
            "numero_version": 1,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-03-29T22:02:38.521876Z",
            "fecha_actualizacion": null,
            "estado": 0,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 8
          }
        ],
        "tipo_documento_nombre": "Tipo 1",
        "especialidad_nombre": "Especialidad 1",
        "sesion_id": null,
        "fecha_creacion": "2023-03-29T22:02:38.518099Z",
        "fecha_actualizacion": null,
        "estado": 1,
        "estado_nom": "Vigente",
        "eliminado": 0
      },
      {
        "id_documento": 7,
        "nombre_documento": "DOCUMENTO 30",
        "codigo_documento": "DOC30",
        "fecha_documento": "2023-03-14",
        "numero_version": 1,
        "documento_general": null,
        "tipo_documento": 1,
        "especialidad": 1,
        "comentario": null,
        "id_empresa": 1,
        "id_version_documento": 13,
        "versiones": [],
        "tipo_documento_nombre": "Tipo 1",
        "especialidad_nombre": "Especialidad 1",
        "sesion_id": null,
        "fecha_creacion": "2023-03-29T21:55:18.761502Z",
        "fecha_actualizacion": null,
        "estado": 1,
        "estado_nom": "Vigente",
        "eliminado": 0
      },
      {
        "id_documento": 6,
        "nombre_documento": "DOCUMENTO 12",
        "codigo_documento": "DOC 123",
        "fecha_documento": "2023-03-08",
        "numero_version": 4,
        "documento_general": null,
        "tipo_documento": 1,
        "especialidad": 1,
        "comentario": null,
        "id_empresa": 1,
        "id_version_documento": 12,
        "versiones": [
          {
            "id_version_documento": 11,
            "estado_nom": "No Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOCUMENTO 12",
            "codigo_documento": "DOC 123",
            "comentario": null,
            "fecha_documento": "2023-03-08",
            "numero_version": 3,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-03-29T21:44:37.008049Z",
            "fecha_actualizacion": null,
            "estado": 0,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 6
          },
          {
            "id_version_documento": 10,
            "estado_nom": "No Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOCUMENTO 12",
            "codigo_documento": "DOC 123",
            "comentario": null,
            "fecha_documento": "2023-03-08",
            "numero_version": 2,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-03-29T21:44:29.534737Z",
            "fecha_actualizacion": null,
            "estado": 0,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 6
          },
          {
            "id_version_documento": 9,
            "estado_nom": "No Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOCUMENTO 12",
            "codigo_documento": "DOC 123",
            "comentario": null,
            "fecha_documento": "2023-03-08",
            "numero_version": 1,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-03-29T21:44:03.529867Z",
            "fecha_actualizacion": null,
            "estado": 0,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 6
          }
        ],
        "tipo_documento_nombre": "Tipo 1",
        "especialidad_nombre": "Especialidad 1",
        "sesion_id": null,
        "fecha_creacion": "2023-03-29T21:44:03.517646Z",
        "fecha_actualizacion": null,
        "estado": 1,
        "estado_nom": "Vigente",
        "eliminado": 0
      },
      {
        "id_documento": 5,
        "nombre_documento": "DOCUMENTO 5",
        "codigo_documento": "DOC5",
        "fecha_documento": "2023-03-29",
        "numero_version": 3,
        "documento_general": null,
        "tipo_documento": 1,
        "especialidad": 1,
        "comentario": null,
        "id_empresa": 1,
        "id_version_documento": 7,
        "versiones": [
          {
            "id_version_documento": 6,
            "estado_nom": "No Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOCUMENTO 5",
            "codigo_documento": "DOC5",
            "comentario": null,
            "fecha_documento": "2023-03-29",
            "numero_version": 2,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-03-29T20:45:22.148467Z",
            "fecha_actualizacion": null,
            "estado": 0,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 5
          },
          {
            "id_version_documento": 5,
            "estado_nom": "No Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOCUMENTO 5",
            "codigo_documento": "DOC5",
            "comentario": null,
            "fecha_documento": "2023-03-29",
            "numero_version": 1,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-03-29T20:41:56.314458Z",
            "fecha_actualizacion": null,
            "estado": 0,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 5
          }
        ],
        "tipo_documento_nombre": "Tipo 1",
        "especialidad_nombre": "Especialidad 1",
        "sesion_id": null,
        "fecha_creacion": "2023-03-29T20:41:56.308752Z",
        "fecha_actualizacion": null,
        "estado": 1,
        "estado_nom": "Vigente",
        "eliminado": 0
      },
      {
        "id_documento": 4,
        "nombre_documento": "DOCUMENTO 4",
        "codigo_documento": "DOC 4",
        "fecha_documento": "2023-03-23",
        "numero_version": 1,
        "documento_general": null,
        "tipo_documento": 1,
        "especialidad": 1,
        "comentario": null,
        "id_empresa": 1,
        "id_version_documento": 4,
        "versiones": [],
        "tipo_documento_nombre": "Tipo 1",
        "especialidad_nombre": "Especialidad 1",
        "sesion_id": null,
        "fecha_creacion": "2023-03-29T20:37:14.330633Z",
        "fecha_actualizacion": null,
        "estado": 1,
        "estado_nom": "Vigente",
        "eliminado": 0
      },
      {
        "id_documento": 3,
        "nombre_documento": "DOCUMENTO 3",
        "codigo_documento": "DOC3",
        "fecha_documento": "2023-04-11",
        "numero_version": 1,
        "documento_general": null,
        "tipo_documento": 1,
        "especialidad": 1,
        "comentario": "null",
        "id_empresa": 1,
        "id_version_documento": 3,
        "versiones": [],
        "tipo_documento_nombre": "Tipo 1",
        "especialidad_nombre": "Especialidad 1",
        "sesion_id": null,
        "fecha_creacion": "2023-03-29T20:32:37.958013Z",
        "fecha_actualizacion": null,
        "estado": 1,
        "estado_nom": "Vigente",
        "eliminado": 0
      },
      {
        "id_documento": 2,
        "nombre_documento": "DOCUMENTO 2",
        "codigo_documento": "DOC2",
        "fecha_documento": "2022-01-06",
        "numero_version": 1,
        "documento_general": null,
        "tipo_documento": 1,
        "especialidad": 1,
        "comentario": "null",
        "id_empresa": 1,
        "id_version_documento": 2,
        "versiones": [],
        "tipo_documento_nombre": "Tipo 1",
        "especialidad_nombre": "Especialidad 1",
        "sesion_id": null,
        "fecha_creacion": "2023-03-29T20:26:18.971123Z",
        "fecha_actualizacion": null,
        "estado": 1,
        "estado_nom": "Vigente",
        "eliminado": 0
      },
      {
        "id_documento": 1,
        "nombre_documento": "DOCUMENTO 1",
        "codigo_documento": "DOC1",
        "fecha_documento": "2023-03-29",
        "numero_version": 2,
        "documento_general": null,
        "tipo_documento": 1,
        "especialidad": 1,
        "comentario": null,
        "id_empresa": 1,
        "id_version_documento": 8,
        "versiones": [
          {
            "id_version_documento": 1,
            "estado_nom": "No Vigente",
            "tipo_documento_nombre": "Tipo 1",
            "especialidad_nombre": "Especialidad 1",
            "nombre_documento": "DOCUMENTO 1",
            "codigo_documento": "DOC1",
            "comentario": null,
            "fecha_documento": "2023-03-29",
            "numero_version": 1,
            "documento_general": null,
            "sesion_id": null,
            "fecha_creacion": "2023-03-29T20:22:34.664724Z",
            "fecha_actualizacion": null,
            "estado": 0,
            "eliminado": 0,
            "tipo_documento": 1,
            "especialidad": 1,
            "documento": 1
          }
        ],
        "tipo_documento_nombre": "Tipo 1",
        "especialidad_nombre": "Especialidad 1",
        "sesion_id": null,
        "fecha_creacion": "2023-03-29T20:22:34.656443Z",
        "fecha_actualizacion": null,
        "estado": 1,
        "estado_nom": "Vigente",
        "eliminado": 0
      }
    ];
  }




}
